### ISSUE TITLE
The fritzing schematic for lesson 12 - dot-matrix display is wrong

### ISSUE THREAD

**Issue by come-maiz** [sunfounder/Sunfounder_SuperKit_for_Arduino#3]
As you can see from the attached screenshot, the dot-matrix display that comes on the fritzing schematic for lesson 12 has only 6 pins on each side. The matrix is 8x8, so there are two missing pins that I don't know where to connect.

![ekrankopio de 2016-12-20 22-45-12](https://cloud.githubusercontent.com/assets/617831/21377830/1f43343a-c707-11e6-8b0f-e57024d67c17.png)

**Comment by come-maiz** [comment]
I was able to complete the lesson with the schematic from https://www.sunfounder.com/learn/Super-Kit-V2-0-for-Arduino/lesson-12-dot-matrix-led-display-super-kit.html

The one I was using before was from the cd that came with the kit.

**Comment by sunfounder** [comment]
Thanks for your notification, the codes and the manual  on CD is old. Please refer to the latest on **LEARN** of our page: https://www.sunfounder.com/learn

**Comment by sunfounder** [comment]
Good to know that. Please feel free to contact us if you have any questions.
